rpi-eeprom-config usr/bin/
rpi-eeprom-update usr/bin/
rpi-eeprom-digest usr/bin/
tools/rpi-bootloader-key-convert usr/bin/
tools/rpi-otp-private-key usr/bin/
tools/rpi-sign-bootcode usr/bin/

debian/default/ etc/

firmware-2711/default usr/lib/firmware/raspberrypi/bootloader-2711/
firmware-2711/latest usr/lib/firmware/raspberrypi/bootloader-2711/

firmware-2711/critical usr/lib/firmware/raspberrypi/bootloader-2711/
firmware-2711/stable usr/lib/firmware/raspberrypi/bootloader-2711/
firmware-2711/beta usr/lib/firmware/raspberrypi/bootloader-2711/

firmware-2711/release-notes.md usr/lib/firmware/raspberrypi/bootloader-2711/

firmware-2712/default usr/lib/firmware/raspberrypi/bootloader-2712/
firmware-2712/latest usr/lib/firmware/raspberrypi/bootloader-2712/

firmware-2712/critical usr/lib/firmware/raspberrypi/bootloader-2712/
firmware-2712/stable usr/lib/firmware/raspberrypi/bootloader-2712/
firmware-2712/beta usr/lib/firmware/raspberrypi/bootloader-2712/

firmware-2712/release-notes.md usr/lib/firmware/raspberrypi/bootloader-2712/
