name: Test EEPROM Config

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Install dependencies
        run: |
          pip install pycryptodomex
      
      - name: Run EEPROM Config Tests
        run: |
          cd test
          chmod +x test-rpi-eeprom-config
          ./test-rpi-eeprom-config 